// ⚠️  GENERATED FILE - DO NOT EDIT
// Generated by 'opensaas generate' from opensaas.config.ts.

import { defineContract } from '@prisma/orm-postgres/contract-builder'
import type { ScalarFieldBuilder } from '@prisma/orm-postgres/contract-builder'
import { timestamptzStringColumn } from '@prisma/orm-postgres/adapter/column-types'

type ModelToken = {
  readonly stageOne: {
    readonly modelName?: string
    readonly fields: Record<string, ScalarFieldBuilder>
  }
}

export const contract = defineContract(
  { extensions: {} },
  ({ field, model, rel }) => {
    const models: Record<string, ModelToken> = {}

    const model_User = (models.User = model('User', {
      fields: {
        id: field.id.uuidv7Native(),
        name: field.text(),
        email: field.text().unique(),
        password: field.text(),
        createdAt: field.temporal.createdAtString(),
        updatedAt: field.temporal.updatedAtString(),
      },
      relations: {
        posts: rel.hasMany(() => models.Post, { by: 'authorId' }),
      },
    }))

    const model_Post = (models.Post = model('Post', {
      fields: {
        id: field.id.uuidv7Native(),
        title: field.text(),
        slug: field.text().unique(),
        content: field.text().optional(),
        internalNotes: field.text().optional(),
        status: field.text().default('draft'),
        publishedAt: field.column(timestamptzStringColumn).optional(),
        authorId: field.uuidNative().optional(),
        createdAt: field.temporal.createdAtString(),
        updatedAt: field.temporal.updatedAtString(),
      },
      relations: {
        author: rel.belongsTo(() => models.User, { from: 'authorId', to: 'id' }),
      },
    }))

    return {
      models: {
        User: model_User.attributes(() => ({
          uniques: [],
        })).sql(() => ({
          indexes: [],
          foreignKeys: [],
        })),
        Post: model_Post.attributes(() => ({
          uniques: [],
        })).sql(({ cols, constraints }) => ({
          indexes: [
            constraints.index([cols.authorId]),
          ],
          foreignKeys: [
            constraints.foreignKey(cols.authorId, model_User.refs.id, { index: false }),
          ],
        })),
      },
    }
  },
)
