// ⚠️  GENERATED FILE - DO NOT EDIT
// Generated by 'opensaas generate' from opensaas.config.ts.

import { defineContract, nativeEnum, pg } from '@prisma/orm-postgres/contract-builder'
import type { ScalarFieldBuilder } from '@prisma/orm-postgres/contract-builder'
import { timestamptzStringColumn } from '@prisma/orm-postgres/adapter/column-types'

type ModelToken = {
  readonly stageOne: {
    readonly modelName?: string
    readonly fields: Record<string, ScalarFieldBuilder>
  }
}

const PostStatusEnum = nativeEnum('PostStatus', 'draft', 'published')

export const contract = defineContract(
  { extensions: {}, namespaces: ['audit'] },
  ({ field, model, rel }) => {
    const models: Record<string, ModelToken> = {}

    const User = (models.User = model('User', {
      fields: {
        id: field.id.uuidv7Native(),
        email: field.text().unique(),
        name: field.text().optional(),
        active: field.boolean().default(true),
        managerId: field.uuidNative().optional().column('manager'),
        createdAt: field.temporal.createdAtString(),
        updatedAt: field.temporal.updatedAtString(),
      },
      relations: {
        posts: rel.hasMany(() => models.Post, { by: 'authorId' }),
        profile: rel.hasOne(() => models.Profile, { by: 'userId' }),
        manager: rel.belongsTo(() => models.User, { from: 'managerId', to: 'id' }),
        reports: rel.hasMany(() => models.User, { by: 'managerId' }),
        from_AuditEntry_actor: rel.hasMany(() => models.AuditEntry, { by: 'actorId' }),
      },
    }))

    const Profile = (models.Profile = model('Profile', {
      fields: {
        id: field.id.uuidv7Native(),
        bio: field.text().optional(),
        userId: field.uuidNative().optional().column('user').unique(),
        createdAt: field.temporal.createdAtString(),
        updatedAt: field.temporal.updatedAtString(),
      },
      relations: {
        user: rel.belongsTo(() => models.User, { from: 'userId', to: 'id' }),
      },
    }))

    const Post = (models.Post = model('Post', {
      fields: {
        id: field.id.uuidv7Native(),
        title: field.text(),
        status: field.column(pg.enum(PostStatusEnum)).default('draft'),
        publishedAt: field.column(timestamptzStringColumn).optional(),
        authorId: field.uuidNative().optional().column('author'),
        categoryId: field.uuidNative().optional().column('category'),
        createdAt: field.temporal.createdAtString(),
        updatedAt: field.temporal.updatedAtString(),
      },
      relations: {
        author: rel.belongsTo(() => models.User, { from: 'authorId', to: 'id' }),
        category: rel.belongsTo(() => models.Category, { from: 'categoryId', to: 'id' }),
      },
    }))

    const Category = (models.Category = model('Category', {
      fields: {
        id: field.id.uuidv7Native(),
        name: field.text().unique(),
      },
      relations: {
        from_Post_category: rel.hasMany(() => models.Post, { by: 'categoryId' }),
      },
    }))

    const AuditEntry = (models.AuditEntry = model('AuditEntry', {
      fields: {
        id: field.id.uuidv7Native(),
        action: field.text(),
        actorId: field.uuidNative().optional().column('actor'),
        createdAt: field.temporal.createdAtString(),
        updatedAt: field.temporal.updatedAtString(),
      },
      relations: {
        actor: rel.belongsTo(() => models.User, { from: 'actorId', to: 'id' }),
      },
      namespace: 'audit',
    }))

    const Settings = (models.Settings = model('Settings', {
      fields: {
        id: field.int().default(1).id(),
        siteName: field.text().optional().default('Fixture'),
        maintenanceMode: field.boolean().default(false),
        createdAt: field.temporal.createdAtString(),
        updatedAt: field.temporal.updatedAtString(),
      },
      relations: {},
    }))

    return {
      models: {
        User: User.attributes(() => ({
          uniques: [],
        })).sql(({ cols, constraints }) => ({
          indexes: [
            constraints.index([cols.managerId]),
          ],
          foreignKeys: [
            constraints.foreignKey(cols.managerId, User.refs.id, { index: false }),
          ],
        })),
        Profile: Profile.attributes(() => ({
          uniques: [],
        })).sql(({ cols, constraints }) => ({
          indexes: [],
          foreignKeys: [
            constraints.foreignKey(cols.userId, User.refs.id, { index: false, onDelete: 'cascade' }),
          ],
        })),
        Post: Post.attributes(() => ({
          uniques: [],
        })).sql(({ cols, constraints }) => ({
          table: 'post',
          indexes: [
            constraints.index([cols.authorId]),
            constraints.index([cols.categoryId]),
            constraints.index([cols.authorId, cols.status], { map: 'post_author_status' }),
          ],
          foreignKeys: [
            constraints.foreignKey(cols.authorId, User.refs.id, { index: false, onDelete: 'setNull' }),
            constraints.foreignKey(cols.categoryId, Category.refs.id, { index: false }),
          ],
        })),
        Category: Category.attributes(() => ({
          uniques: [],
        })).sql(() => ({
          indexes: [],
          foreignKeys: [],
        })),
        AuditEntry: AuditEntry.attributes(() => ({
          uniques: [],
        })).sql(({ cols, constraints }) => ({
          indexes: [
            constraints.index([cols.actorId]),
          ],
          foreignKeys: [
            constraints.foreignKey(cols.actorId, User.refs.id, { index: false }),
          ],
        })),
        Settings: Settings.attributes(() => ({
          uniques: [],
        })).sql(() => ({
          indexes: [],
          foreignKeys: [],
        })),
      },
    }
  },
)
