// ⚠️  GENERATED FILE - DO NOT EDIT
// Generated by 'opensaas generate' from opensaas.config.ts.

import { defineContract } from '@prisma/orm-postgres/contract-builder'
import type { ScalarFieldBuilder } from '@prisma/orm-postgres/contract-builder'

type ModelToken = {
  readonly stageOne: {
    readonly modelName?: string
    readonly fields: Record<string, ScalarFieldBuilder>
  }
}

export const contract = defineContract(
  { extensions: {} },
  ({ field, model }) => {
    const models: Record<string, ModelToken> = {}

    const model_Product = (models.Product = model('Product', {
      fields: {
        id: field.id.uuidv7Native(),
        name: field.text(),
        metadata: field.json().optional(),
        settings: field.json().optional(),
        configuration: field.json(),
      },
      relations: {},
    }))

    const model_Article = (models.Article = model('Article', {
      fields: {
        id: field.id.uuidv7Native(),
        title: field.text(),
        content: field.json().optional(),
        taxonomy: field.json().optional(),
      },
      relations: {},
    }))

    return {
      models: {
        Product: model_Product.attributes(() => ({
          uniques: [],
        })).sql(() => ({
          indexes: [],
          foreignKeys: [],
        })),
        Article: model_Article.attributes(() => ({
          uniques: [],
        })).sql(() => ({
          indexes: [],
          foreignKeys: [],
        })),
      },
    }
  },
)
