packages:
  - packages/*
  - examples/*
  - docs

onlyBuiltDependencies:
  - better-sqlite3

ignoredBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
