/**
 * Convert Better Auth database schema to OpenSaaS list configs
 * Allows dynamic list generation from Better Auth plugins
 */

import { list } from '@opensaas/stack-core'
import { text, timestamp, checkbox, integer } from '@opensaas/stack-core/fields'
import type { ListConfig, FieldConfig } from '@opensaas/stack-core'

/**
 * Better Auth field attribute structure
 * Inferred from better-auth internal types
 */
type BetterAuthFieldAttribute = {
  type: string // 'string' | 'number' | 'boolean' | 'date' | etc.
  required?: boolean
  unique?: boolean
  references?: {
    model: string
    field: string
    onDelete?: 'cascade' | 'set null' | 'restrict'
  }
  defaultValue?: unknown
  returned?: boolean
  input?: boolean
}

/**
 * Better Auth table schema structure
 */
type BetterAuthTableSchema = {
  modelName: string
  fields: Record<string, BetterAuthFieldAttribute>
}

/**
 * Convert Better Auth field type to OpenSaaS field config
 */
function convertField(
  fieldName: string,
  betterAuthField: BetterAuthFieldAttribute,
): FieldConfig | null {
  const { type, required, unique, defaultValue, references } = betterAuthField

  // System fields are auto-generated by OpenSaaS
  if (fieldName === 'id' || fieldName === 'createdAt' || fieldName === 'updatedAt') {
    return null
  }

  // Handle references (relationships)
  if (references) {
    // Relationships are handled separately
    // Return null here and handle in relationship pass
    return null
  }

  // Map Better Auth types to OpenSaaS field types
  switch (type) {
    case 'string':
      return text({
        validation: { isRequired: required },
        isIndexed: unique ? 'unique' : undefined,
        defaultValue: typeof defaultValue === 'string' ? defaultValue : undefined,
      })

    case 'number':
      return integer({
        validation: { isRequired: required },
        defaultValue: typeof defaultValue === 'number' ? defaultValue : undefined,
      })

    case 'boolean':
      return checkbox({
        defaultValue: typeof defaultValue === 'boolean' ? defaultValue : false,
      })

    case 'date':
      return timestamp({
        defaultValue: defaultValue === 'now' ? { kind: 'now' } : undefined,
      })

    default:
      // Unknown type - default to text
      console.warn(
        `[stack-auth] Unknown Better Auth field type "${type}" for field "${fieldName}", defaulting to text field`,
      )
      return text({
        validation: { isRequired: required },
      })
  }
}

/**
 * Get default access control for auth tables
 * Most auth tables should only be accessible to their owners
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any -- ListConfig must accept any TypeInfo
function getDefaultAccess(tableName: string): ListConfig<any>['access'] {
  const lowerTableName = tableName.toLowerCase()

  // User table - special access control
  if (lowerTableName === 'user') {
    return {
      operation: {
        query: () => true, // Anyone can query users
        create: () => true, // Anyone can create (sign up)
        // eslint-disable-next-line @typescript-eslint/no-explicit-any -- Access control parameters are runtime values
        update: ({ session, item }: any) => {
          if (!session) return false
          const userId = (session as { userId?: string }).userId
          const itemId = (item as { id?: string })?.id
          return userId === itemId
        },
        // eslint-disable-next-line @typescript-eslint/no-explicit-any -- Access control parameters are runtime values
        delete: ({ session, item }: any) => {
          if (!session) return false
          const userId = (session as { userId?: string }).userId
          const itemId = (item as { id?: string })?.id
          return userId === itemId
        },
      },
    }
  }

  // Session table
  if (lowerTableName === 'session') {
    return {
      operation: {
        // eslint-disable-next-line @typescript-eslint/no-explicit-any -- Access control parameters are runtime values
        query: ({ session }: any) => {
          if (!session) return false
          const userId = (session as { userId?: string }).userId
          if (!userId) return false
          return {
            user: { id: { equals: userId } },
          } as Record<string, unknown>
        },
        create: () => true, // Better-auth handles session creation
        update: () => false, // No manual updates
        // eslint-disable-next-line @typescript-eslint/no-explicit-any -- Access control parameters are runtime values
        delete: ({ session, item }: any) => {
          if (!session) return false
          const userId = (session as { userId?: string }).userId
          const itemUserId = (item as { user?: { id?: string } })?.user?.id
          return userId === itemUserId
        },
      },
    }
  }

  // Account table
  if (lowerTableName === 'account') {
    return {
      operation: {
        // eslint-disable-next-line @typescript-eslint/no-explicit-any -- Access control parameters are runtime values
        query: ({ session }: any) => {
          if (!session) return false
          const userId = (session as { userId?: string }).userId
          if (!userId) return false
          return {
            user: { id: { equals: userId } },
          } as Record<string, unknown>
        },
        create: () => true, // Better-auth handles account creation
        // eslint-disable-next-line @typescript-eslint/no-explicit-any -- Access control parameters are runtime values
        update: ({ session, item }: any) => {
          if (!session) return false
          const userId = (session as { userId?: string }).userId
          const itemUserId = (item as { user?: { id?: string } })?.user?.id
          return userId === itemUserId
        },
        // eslint-disable-next-line @typescript-eslint/no-explicit-any -- Access control parameters are runtime values
        delete: ({ session, item }: any) => {
          if (!session) return false
          const userId = (session as { userId?: string }).userId
          const itemUserId = (item as { user?: { id?: string } })?.user?.id
          return userId === itemUserId
        },
      },
    }
  }

  // Verification table
  if (lowerTableName === 'verification') {
    return {
      operation: {
        query: () => false, // No public querying
        create: () => true, // Better-auth creates verification tokens
        update: () => false, // No updates
        delete: () => true, // Better-auth deletes used/expired tokens
      },
    }
  }

  // OAuth tables (from MCP/OIDC plugins)
  if (
    lowerTableName === 'oauthapplication' ||
    lowerTableName === 'oauthaccesstoken' ||
    lowerTableName === 'oauthconsent'
  ) {
    return {
      operation: {
        // eslint-disable-next-line @typescript-eslint/no-explicit-any -- Access control parameters are runtime values
        query: ({ session }: any) => {
          if (!session) return false
          const userId = (session as { userId?: string }).userId
          if (!userId) return false
          // Filter by userId if field exists
          return {
            userId: { equals: userId },
          } as Record<string, unknown>
        },
        create: () => true, // Better-auth/plugins handle creation
        // eslint-disable-next-line @typescript-eslint/no-explicit-any -- Access control parameters are runtime values
        update: ({ session, item }: any) => {
          if (!session) return false
          const userId = (session as { userId?: string }).userId
          const itemUserId = (item as { userId?: string })?.userId
          return userId === itemUserId
        },
        // eslint-disable-next-line @typescript-eslint/no-explicit-any -- Access control parameters are runtime values
        delete: ({ session, item }: any) => {
          if (!session) return false
          const userId = (session as { userId?: string }).userId
          const itemUserId = (item as { userId?: string })?.userId
          return userId === itemUserId
        },
      },
    }
  }

  // Default: restrict all access (safest default)
  return {
    operation: {
      query: () => false,
      create: () => false,
      update: () => false,
      delete: () => false,
    },
  }
}

/**
 * Convert Better Auth table schema to OpenSaaS ListConfig
 */
export function convertTableToList(
  tableName: string,
  tableSchema: BetterAuthTableSchema,
): ListConfig<any> {
  // eslint-disable-line @typescript-eslint/no-explicit-any -- ListConfig must accept any TypeInfo
  const fields: Record<string, FieldConfig> = {}

  // First pass: convert regular fields
  for (const [fieldName, fieldAttr] of Object.entries(tableSchema.fields)) {
    const fieldConfig = convertField(fieldName, fieldAttr)
    if (fieldConfig) {
      fields[fieldName] = fieldConfig
    }
  }

  // Second pass: add relationships
  // NOTE: Better Auth uses one-way references, but OpenSaaS requires bidirectional relationships
  // We skip relationship conversion for now and rely on the foreign key fields
  // Users can manually add bidirectional relationships if needed by extending the User list
  for (const [fieldName, fieldAttr] of Object.entries(tableSchema.fields)) {
    if (fieldAttr.references) {
      // For now, treat reference fields as regular text fields (foreign keys)
      // This preserves the userId, clientId, etc. fields that Better Auth expects
      if (!fields[fieldName]) {
        fields[fieldName] = text({
          validation: { isRequired: fieldAttr.required },
        })
      }
    }
  }

  // Create list config with default access control
  return list({
    fields,
    access: getDefaultAccess(tableName),
  })
}

/**
 * Convert all Better Auth tables to OpenSaaS list configs
 * This is called by withAuth() to generate lists from Better Auth + plugins
 */
export function convertBetterAuthSchema(
  tables: Record<string, BetterAuthTableSchema>,
): Record<string, ListConfig<any>> {
  // eslint-disable-line @typescript-eslint/no-explicit-any -- ListConfig must accept any TypeInfo
  const lists: Record<string, ListConfig<any>> = {} // eslint-disable-line @typescript-eslint/no-explicit-any -- ListConfig must accept any TypeInfo

  for (const [tableName, tableSchema] of Object.entries(tables)) {
    // Convert table name to PascalCase for OpenSaaS list key
    const listKey = tableSchema.modelName || toPascalCase(tableName)
    lists[listKey] = convertTableToList(tableName, tableSchema)
  }

  return lists
}

/**
 * Convert table name to PascalCase
 * e.g., "oauth_application" -> "OauthApplication"
 */
function toPascalCase(str: string): string {
  return str
    .split(/[_-]/)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join('')
}
