/**
 * Convert Better Auth database schema to OpenSaaS list configs
 * Allows dynamic list generation from Better Auth plugins
 */

import { list } from '@opensaas/stack-core'
import { text, timestamp, checkbox, integer } from '@opensaas/stack-core/fields'
import type { ListConfig, FieldConfig } from '@opensaas/stack-core'

/**
 * Better Auth field attribute structure
 * Inferred from better-auth internal types
 */
type BetterAuthFieldAttribute = {
  type: string | string[] // 'string' | 'number' | 'boolean' | 'date' | etc., or an enum array
  required?: boolean
  unique?: boolean
  references?: {
    model: string
    field: string
    onDelete?: 'no action' | 'restrict' | 'cascade' | 'set null' | 'set default'
  }
  defaultValue?: unknown
  returned?: boolean
  input?: boolean
}

/**
 * Better Auth table schema structure
 */
type BetterAuthTableSchema = {
  modelName?: string
  fields: Record<string, BetterAuthFieldAttribute>
}

/**
 * Convert Better Auth field type to OpenSaaS field config
 */
function convertField(
  fieldName: string,
  betterAuthField: BetterAuthFieldAttribute,
): FieldConfig | null {
  const { type, required, unique, defaultValue, references } = betterAuthField

  // System fields are auto-generated by OpenSaaS
  if (fieldName === 'id' || fieldName === 'createdAt' || fieldName === 'updatedAt') {
    return null
  }

  // Handle references (relationships)
  if (references) {
    // Relationships are handled separately
    // Return null here and handle in relationship pass
    return null
  }

  // Map Better Auth types to OpenSaaS field types
  switch (type) {
    case 'string':
      return text({
        validation: { isRequired: required },
        isIndexed: unique ? 'unique' : undefined,
        defaultValue: typeof defaultValue === 'string' ? defaultValue : undefined,
      })

    case 'number':
      return integer({
        validation: { isRequired: required },
        defaultValue: typeof defaultValue === 'number' ? defaultValue : undefined,
      })

    case 'boolean':
      return checkbox({
        defaultValue: typeof defaultValue === 'boolean' ? defaultValue : false,
      })

    case 'date':
      return timestamp({
        defaultValue: defaultValue === 'now' ? { kind: 'now' } : undefined,
      })

    default:
      // Unknown type - default to text
      console.warn(
        `[stack-auth] Unknown Better Auth field type "${type}" for field "${fieldName}", defaulting to text field`,
      )
      return text({
        validation: { isRequired: required },
      })
  }
}

/**
 * Convert Better Auth table schema to OpenSaaS ListConfig.
 *
 * Per ADR-0013, plugin-injected lists ship **closed** — no access is set here,
 * so the list denies every operation until the application grants it. For a
 * table that resolves onto one of the four base auth models (user/session/
 * account/verification), that means `authPlugin({ access: { ... } })`; for any
 * other better-auth-plugin-declared table (e.g. OAuth client tables from the
 * `mcp` plugin), the application must declare the list itself under the same
 * derived key so the plugin's field-only extend path can merge in (its access
 * then stands untouched).
 */
export function convertTableToList(
  tableName: string,
  tableSchema: BetterAuthTableSchema,
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- ListConfig must accept any TypeInfo
): ListConfig<any> {
  const fields: Record<string, FieldConfig> = {}

  // First pass: convert regular fields
  for (const [fieldName, fieldAttr] of Object.entries(tableSchema.fields)) {
    const fieldConfig = convertField(fieldName, fieldAttr)
    if (fieldConfig) {
      fields[fieldName] = fieldConfig
    }
  }

  // Second pass: add relationships
  // NOTE: Better Auth uses one-way references, but OpenSaaS requires bidirectional relationships
  // We skip relationship conversion for now and rely on the foreign key fields
  // Users can manually add bidirectional relationships if needed by extending the User list
  for (const [fieldName, fieldAttr] of Object.entries(tableSchema.fields)) {
    if (fieldAttr.references) {
      // For now, treat reference fields as regular text fields (foreign keys)
      // This preserves the userId, clientId, etc. fields that Better Auth expects
      if (!fields[fieldName]) {
        fields[fieldName] = text({
          validation: { isRequired: fieldAttr.required },
        })
      }
    }
  }

  return list({ fields })
}

/**
 * Base better-auth model keys — the four tables the auth plugin's own model
 * config (`user`/`session`/`account`/`verification`) can remap via `modelName`.
 */
type BaseAuthModelKey = 'user' | 'session' | 'account' | 'verification'

/**
 * Resolved list key for each base better-auth model, as derived by
 * {@link deriveAuthLists} from the plugin's configured model-key remap (e.g.
 * `user.modelName: 'AuthUser'`). Passed to {@link convertBetterAuthSchema} so a
 * provider plugin's schema extension of a base model (e.g. `user`) lands on the
 * same adopted Auth list rather than being re-derived from the plugin's own
 * table name.
 */
export type BaseAuthModelKeys = Partial<Record<BaseAuthModelKey, string>>

/**
 * Look up the configured remap for a table name, if it names one of the four
 * base better-auth models (case-insensitively). Written as an explicit switch
 * rather than an indexed lookup so no type assertion is needed to narrow the
 * table name into {@link BaseAuthModelKey}.
 */
function resolveBaseModelKey(
  tableName: string,
  baseModelKeys: BaseAuthModelKeys,
): string | undefined {
  switch (tableName.toLowerCase()) {
    case 'user':
      return baseModelKeys.user
    case 'session':
      return baseModelKeys.session
    case 'account':
      return baseModelKeys.account
    case 'verification':
      return baseModelKeys.verification
    default:
      return undefined
  }
}

/**
 * Convert all Better Auth tables to OpenSaaS list configs
 * This is called by authPlugin() to generate lists from Better Auth + plugins
 *
 * @param tables - The better-auth plugin's declared schema extension
 * @param baseModelKeys - The resolved list keys for the four base auth models
 *   (`user`/`session`/`account`/`verification`), from the same model-key remap
 *   the Auth lists themselves use. When a table name matches one of these keys
 *   (case-insensitively), its list key is taken from here instead of being
 *   re-derived from the table name — so a schema extension targeting `user`
 *   lands on the adopted Auth list (e.g. `AuthUser`) rather than a re-derived
 *   `User`, even when that key collides with an unrelated host list.
 */
export function convertBetterAuthSchema(
  tables: Record<string, BetterAuthTableSchema>,
  baseModelKeys: BaseAuthModelKeys = {},
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- ListConfig must accept any TypeInfo
): Record<string, ListConfig<any>> {
  const lists: Record<string, ListConfig<any>> = {} // eslint-disable-line @typescript-eslint/no-explicit-any -- ListConfig must accept any TypeInfo

  for (const [tableName, tableSchema] of Object.entries(tables)) {
    // A base-model remap always wins: it reflects the actual configured list
    // key for that model, whereas `tableSchema.modelName`/the table name are
    // just how the provider plugin happens to describe its own extension.
    const listKey =
      resolveBaseModelKey(tableName, baseModelKeys) ||
      tableSchema.modelName ||
      toPascalCase(tableName)
    lists[listKey] = convertTableToList(tableName, tableSchema)
  }

  return lists
}

/**
 * Convert table name to PascalCase
 * e.g., "oauth_application" -> "OauthApplication"
 */
function toPascalCase(str: string): string {
  return str
    .split(/[_-]/)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join('')
}
