import { describe, it, expect, beforeAll, afterAll } from 'vitest'
import { execFile } from 'node:child_process'
import { promisify } from 'node:util'
import fs from 'fs-extra'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { generateEnvFiles } from '../src/lib/env.js'

/**
 * End-to-end smoke test for the first-run flow.
 *
 * The basic template is `examples/starter`, which is workspace-linked and so
 * has the toolchain (`opensaas` CLI, Prisma, the SQLite adapter) resolvable.
 * We write the same runnable `.env` the scaffolder produces, then run the two
 * documented setup steps — `generate` and `db:push` — and assert the project
 * artifacts appear. This guarantees a scaffolded SQLite project reaches a
 * working database with no manual edits.
 *
 * It is skipped when the CLI hasn't been built yet (the example's `generate`
 * script invokes the `opensaas` binary), so a bare `vitest` run without a
 * prior `pnpm build` does not fail spuriously. CI builds before testing.
 */

const run = promisify(execFile)
const here = path.dirname(fileURLToPath(import.meta.url))
const repoRoot = path.resolve(here, '../../..')
const starterDir = path.join(repoRoot, 'examples/starter')
const cliBin = path.join(repoRoot, 'packages/cli/dist/index.js')

const prerequisitesPresent = fs.existsSync(starterDir) && fs.existsSync(cliBin)

const generatedArtifacts = ['.opensaas', 'dev.db', 'prisma/schema.prisma']

async function cleanStarter(originalSchema: string): Promise<void> {
  for (const artifact of ['.opensaas', 'dev.db']) {
    await fs.remove(path.join(starterDir, artifact))
  }
  await fs.writeFile(path.join(starterDir, '.env'), '')
  // The committed schema is regenerated by `generate`; restore its content.
  await fs.writeFile(path.join(starterDir, 'prisma/schema.prisma'), originalSchema)
}

describe.skipIf(!prerequisitesPresent)('scaffold smoke: generate + db:push (SQLite)', () => {
  let originalSchema = ''

  beforeAll(async () => {
    originalSchema = await fs.readFile(path.join(starterDir, 'prisma/schema.prisma'), 'utf-8')
    // Write exactly what the scaffolder writes for a SQLite project.
    const { env } = generateEnvFiles({ provider: 'sqlite', projectName: 'starter' })
    await fs.writeFile(path.join(starterDir, '.env'), env)
  }, 30_000)

  afterAll(async () => {
    await cleanStarter(originalSchema)
  })

  it('reaches a working database with no manual .env edits', async () => {
    // `pnpm --filter <pkg> run <script>` resolves the workspace toolchain
    // regardless of cwd.
    await run('pnpm', ['--filter', 'opensaas-starter-example', 'run', 'generate'], {
      cwd: repoRoot,
    })
    await run('pnpm', ['--filter', 'opensaas-starter-example', 'run', 'db:push'], {
      cwd: repoRoot,
    })

    expect(fs.existsSync(path.join(starterDir, '.opensaas/context.ts'))).toBe(true)
    expect(fs.existsSync(path.join(starterDir, 'dev.db'))).toBe(true)
  }, 180_000)
})

// Surface, in a normal unit run, why the heavier test was skipped.
describe.runIf(!prerequisitesPresent)('scaffold smoke (skipped)', () => {
  it('is skipped until the CLI is built (run `pnpm build` first)', () => {
    expect(generatedArtifacts.length).toBeGreaterThan(0)
  })
})
