import type { OpenSaasConfig } from '@opensaas/stack-core'
import * as fs from 'fs'
import * as path from 'path'

/**
 * Generate context factory that abstracts Prisma client from developers
 *
 * Creates a simple API with getContext() and getContextWithSession(session)
 * that internally handles Prisma singleton and config imports.
 */
export function generateContext(config: OpenSaasConfig): string {
  // Check if custom Prisma client constructor is provided
  const hasCustomConstructor = !!config.db.prismaClientConstructor

  // Check if storage is configured
  const hasStorage = !!config.storage && Object.keys(config.storage).length > 0

  // Generate the Prisma client instantiation code
  const prismaInstantiation = hasCustomConstructor
    ? `config.db.prismaClientConstructor!(PrismaClient)`
    : `new PrismaClient()`

  // Generate storage utilities if storage is configured
  const storageUtilities = hasStorage
    ? `
/**
 * Lazy-loaded storage runtime functions
 * Prevents sharp and other storage dependencies from being bundled in client code
 */
let storageRuntime: typeof import('@opensaas/stack-storage/runtime') | null = null

async function getStorageRuntime() {
  if (!storageRuntime) {
    try {
      storageRuntime = await import('@opensaas/stack-storage/runtime')
    } catch (error) {
      throw new Error(
        'Failed to load @opensaas/stack-storage/runtime. Make sure @opensaas/stack-storage is installed.'
      )
    }
  }
  return storageRuntime
}

/**
 * Storage utilities for file/image uploads
 */
const storage = {
  uploadFile: async (providerName: string, file: File, buffer: Buffer, options?: unknown) => {
    const runtime = await getStorageRuntime()
    return runtime.uploadFile(config, providerName, { file, buffer }, options as any)
  },

  uploadImage: async (providerName: string, file: File, buffer: Buffer, options?: unknown) => {
    const runtime = await getStorageRuntime()
    return runtime.uploadImage(config, providerName, { file, buffer }, options as any)
  },

  deleteFile: async (providerName: string, filename: string) => {
    const runtime = await getStorageRuntime()
    return runtime.deleteFile(config, providerName, filename)
  },

  deleteImage: async (metadata: unknown) => {
    const runtime = await getStorageRuntime()
    return runtime.deleteImage(config, metadata as any)
  },
}
`
    : `
/**
 * Storage utilities (not configured)
 */
const storage = {
  uploadFile: async () => {
    throw new Error('Storage is not configured. Add storage providers to your opensaas.config.ts')
  },
  uploadImage: async () => {
    throw new Error('Storage is not configured. Add storage providers to your opensaas.config.ts')
  },
  deleteFile: async () => {
    throw new Error('Storage is not configured. Add storage providers to your opensaas.config.ts')
  },
  deleteImage: async () => {
    throw new Error('Storage is not configured. Add storage providers to your opensaas.config.ts')
  },
}
`

  return `/**
 * Auto-generated context factory
 *
 * This module provides a simple API for creating OpenSaas contexts.
 * It abstracts away Prisma client management and configuration.
 *
 * DO NOT EDIT - This file is automatically generated by 'pnpm generate'
 */

import { getContext as getOpensaasContext } from '@opensaas/stack-core'
import { PrismaClient } from './prisma-client'
import config from '../opensaas.config'

// Internal Prisma singleton - managed automatically
const globalForPrisma = globalThis as unknown as { prisma: PrismaClient | undefined }
const prisma = globalForPrisma.prisma ?? ${prismaInstantiation}
if (process.env.NODE_ENV !== 'production') globalForPrisma.prisma = prisma
${storageUtilities}
/**
 * Get OpenSaas context with optional session
 *
 * @param session - Optional session object (structure defined by your application)
 *
 * @example
 * \`\`\`typescript
 * // Anonymous access
 * const context = getContext()
 * const posts = await context.db.post.findMany()
 *
 * // Authenticated access
 * const context = getContext({ userId: 'user-123' })
 * const myPosts = await context.db.post.findMany()
 * \`\`\`
 */
export function getContext(session?: { userId?: string; [key: string]: unknown } | null) {
  return getOpensaasContext(config, prisma, session ?? null, storage)
}

export const rawOpensaasContext = getContext()
`
}

/**
 * Write context factory to file
 */
export function writeContext(config: OpenSaasConfig, outputPath: string): void {
  const content = generateContext(config)

  // Ensure directory exists
  const dir = path.dirname(outputPath)
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true })
  }

  fs.writeFileSync(outputPath, content, 'utf-8')
}
