import type { OpenSaasConfig } from '@opensaas/stack-core'
import * as fs from 'fs'
import * as path from 'path'
import { collectNeeds } from './types.js'

function capitalize(value: string): string {
  return value.charAt(0).toUpperCase() + value.slice(1)
}

/**
 * Map a field type string to the TypeScript field-config type and the
 * `@opensaas/stack-core` entry point it is exported from.
 *
 * Built-in field types and their config types live on the `/fields` entry
 * point. Unknown field types (e.g. those contributed by plugins) fall back to
 * the generic `BaseFieldConfig`, exported from the `/extend` authoring surface.
 */
function getFieldTypeImport(fieldType: string): { module: string; typeName: string } {
  const typeMap: Record<string, string> = {
    text: 'TextField',
    integer: 'IntegerField',
    decimal: 'DecimalField',
    bigInt: 'BigIntField',
    checkbox: 'CheckboxField',
    timestamp: 'TimestampField',
    calendarDay: 'CalendarDayField',
    password: 'PasswordField',
    select: 'SelectField',
    relationship: 'RelationshipField',
    json: 'JsonField',
    virtual: 'VirtualField',
  }

  const typeName = typeMap[fieldType]
  if (typeName) {
    return { module: '@opensaas/stack-core/fields', typeName }
  }

  return { module: '@opensaas/stack-core/extend', typeName: 'BaseFieldConfig' }
}

/**
 * Generates the `Lists` namespace: TypeInfo for each list, giving hooks
 * strongly-typed access to Prisma input types.
 *
 * @example
 * ```typescript
 * // Generated output:
 * export declare namespace Lists {
 *   export type Post = import('@opensaas/stack-core').ListConfig<Lists.Post.TypeInfo>
 *
 *   namespace Post {
 *     export type Item = import('./types.ts').Post
 *     export type TypeInfo = {
 *       key: 'Post'
 *       item: Item
 *       inputs: {
 *         create: import('./types.ts').PostCreateInput
 *         update: import('./types.ts').PostUpdateInput
 *       }
 *     }
 *   }
 * }
 * ```
 */
export function generateListsNamespace(config: OpenSaasConfig): string {
  const lines: string[] = []

  lines.push('/**')
  lines.push(' * Generated Lists namespace from OpenSaas configuration')
  lines.push(' * DO NOT EDIT - This file is automatically generated')
  lines.push(' *')
  lines.push(' * This file provides TypeInfo for each list, enabling strong typing')
  lines.push(' * for hooks with Prisma input types.')
  lines.push(' *')
  lines.push(' * @example')
  lines.push(' * ```typescript')
  lines.push(" * import type { Lists } from './.opensaas/lists'")
  lines.push(' *')
  lines.push(' * // Use TypeInfo as generic parameter')
  lines.push(' * Post: list<Lists.Post.TypeInfo>({')
  lines.push(' *   hooks: {')
  lines.push(' *     resolveInput: async ({ operation, resolvedData }) => {')
  lines.push(' *       // resolvedData is Prisma.PostCreateInput or Prisma.PostUpdateInput')
  lines.push(' *       return resolvedData')
  lines.push(' *     }')
  lines.push(' *   }')
  lines.push(' * })')
  lines.push(' *')
  lines.push(' * // Or use as typed constant')
  lines.push(' * const Post: Lists.Post = list({ ... })')
  lines.push(' * ```')
  lines.push(' */')
  lines.push('')

  lines.push('export declare namespace Lists {')

  for (const [listName, listConfig] of Object.entries(config.lists)) {
    lines.push(
      `  export type ${listName} = import('@opensaas/stack-core').ListConfig<Lists.${listName}.TypeInfo>`,
    )
    lines.push('')
    lines.push(`  namespace ${listName} {`)
    // A hook's \`item\` is the STORED row: it runs before \`resolveOutput\`, so a
    // type carrying computed keys would promise a value it never sees (ADR-0027).
    lines.push(`    export type Item = import('./types.ts').${listName}StoredRow`)
    lines.push('')

    lines.push(`    /**`)
    lines.push(`     * Field configurations for ${listName}`)
    lines.push(`     * Maps field names to their field config types`)
    lines.push(`     */`)
    lines.push(`    export type Fields = {`)
    for (const [fieldName, fieldConfig] of Object.entries(listConfig.fields)) {
      const { module, typeName } = getFieldTypeImport(fieldConfig.type)
      lines.push(`      ${fieldName}: import('${module}').${typeName}<Lists.${listName}.TypeInfo>`)
    }
    lines.push(`    }`)
    lines.push('')

    lines.push(`    /**`)
    lines.push(`     * Per-field declared-dependency facts (ADR-0051). \`needs\` is what the`)
    lines.push(`     * field declared; \`item\` is that set resolved against the contract —`)
    lines.push(`     * exactly what its \`resolveOutput\` hook is handed.`)
    lines.push(`     */`)
    lines.push(`    export type Needs = {`)
    for (const [fieldName, keys] of collectNeeds(listConfig.fields)) {
      const union = keys.map((key) => `'${key}'`).join(' | ')
      const itemType = `import('./types.ts').${listName}${capitalize(fieldName)}NeedsItem`
      lines.push(`      ${fieldName}: { needs: ${union}; item: ${itemType} }`)
    }
    lines.push(`    }`)
    lines.push('')

    lines.push(`    export type TypeInfo = {`)
    lines.push(`      key: '${listName}'`)
    lines.push(`      fields: Fields`)
    lines.push(`      needs: Needs`)
    lines.push(`      item: Item`)
    lines.push(`      output: import('./types.ts').${listName}`)
    lines.push(`      inputs: {`)
    lines.push(`        create: import('./types.ts').${listName}CreateInput`)
    lines.push(`        update: import('./types.ts').${listName}UpdateInput`)
    lines.push(`      }`)
    lines.push(`    }`)
    lines.push(`  }`)
    lines.push('')
  }

  lines.push('}')

  return lines.join('\n')
}

export function writeLists(config: OpenSaasConfig, outputPath: string): void {
  const lists = generateListsNamespace(config)

  const dir = path.dirname(outputPath)
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true })
  }

  fs.writeFileSync(outputPath, lists, 'utf-8')
}
