import type { OpenSaasConfig } from '@opensaas/stack-core'
import * as fs from 'fs'
import * as path from 'path'

/**
 * Map field type string to TypeScript field type name
 */
function getFieldTypeName(fieldType: string): string {
  const typeMap: Record<string, string> = {
    text: 'TextField',
    integer: 'IntegerField',
    checkbox: 'CheckboxField',
    timestamp: 'TimestampField',
    password: 'PasswordField',
    select: 'SelectField',
    relationship: 'RelationshipField',
    json: 'JsonField',
    virtual: 'VirtualField',
  }

  return typeMap[fieldType] || 'BaseFieldConfig'
}

/**
 * Generate Lists namespace with TypeInfo for each list
 * This provides strongly-typed hooks with Prisma input types
 *
 * @example
 * ```typescript
 * // Generated output:
 * export declare namespace Lists {
 *   export type Post = import('@opensaas/stack-core').ListConfig<Lists.Post.TypeInfo>
 *
 *   namespace Post {
 *     export type Item = import('./types').Post
 *     export type TypeInfo = {
 *       key: 'Post'
 *       item: Item
 *       inputs: {
 *         create: import('./prisma-client/client').Prisma.PostCreateInput
 *         update: import('./prisma-client/client').Prisma.PostUpdateInput
 *       }
 *     }
 *   }
 * }
 * ```
 */
export function generateListsNamespace(config: OpenSaasConfig): string {
  const lines: string[] = []

  // Add header comment
  lines.push('/**')
  lines.push(' * Generated Lists namespace from OpenSaas configuration')
  lines.push(' * DO NOT EDIT - This file is automatically generated')
  lines.push(' *')
  lines.push(' * This file provides TypeInfo for each list, enabling strong typing')
  lines.push(' * for hooks with Prisma input types.')
  lines.push(' *')
  lines.push(' * @example')
  lines.push(' * ```typescript')
  lines.push(" * import type { Lists } from './.opensaas/lists'")
  lines.push(' *')
  lines.push(' * // Use TypeInfo as generic parameter')
  lines.push(' * Post: list<Lists.Post.TypeInfo>({')
  lines.push(' *   hooks: {')
  lines.push(' *     resolveInput: async ({ operation, resolvedData }) => {')
  lines.push(' *       // resolvedData is Prisma.PostCreateInput or Prisma.PostUpdateInput')
  lines.push(' *       return resolvedData')
  lines.push(' *     }')
  lines.push(' *   }')
  lines.push(' * })')
  lines.push(' *')
  lines.push(' * // Or use as typed constant')
  lines.push(' * const Post: Lists.Post = list({ ... })')
  lines.push(' * ```')
  lines.push(' */')
  lines.push('')

  // Start Lists namespace
  lines.push('export declare namespace Lists {')

  // Generate type for each list
  for (const [listName, listConfig] of Object.entries(config.lists)) {
    lines.push(
      `  export type ${listName} = import('@opensaas/stack-core').ListConfig<Lists.${listName}.TypeInfo>`,
    )
    lines.push('')
    lines.push(`  namespace ${listName} {`)
    lines.push(`    export type Item = import('./types').${listName}`)
    lines.push('')

    // Generate Fields type
    lines.push(`    /**`)
    lines.push(`     * Field configurations for ${listName}`)
    lines.push(`     * Maps field names to their field config types`)
    lines.push(`     */`)
    lines.push(`    export type Fields = {`)
    for (const [fieldName, fieldConfig] of Object.entries(listConfig.fields)) {
      const fieldTypeName = getFieldTypeName(fieldConfig.type)
      lines.push(
        `      ${fieldName}: import('@opensaas/stack-core').${fieldTypeName}<Lists.${listName}.TypeInfo>`,
      )
    }
    lines.push(`    }`)
    lines.push('')

    // Generate TypeInfo with fields property
    lines.push(`    export type TypeInfo = {`)
    lines.push(`      key: '${listName}'`)
    lines.push(`      fields: Fields`)
    lines.push(`      item: Item`)
    lines.push(`      inputs: {`)
    lines.push(`        create: import('./prisma-client/client').Prisma.${listName}CreateInput`)
    lines.push(`        update: import('./prisma-client/client').Prisma.${listName}UpdateInput`)
    lines.push(`      }`)
    lines.push(`    }`)
    lines.push(`  }`)
    lines.push('')
  }

  // Close Lists namespace
  lines.push('}')

  return lines.join('\n')
}

/**
 * Write Lists namespace to file
 */
export function writeLists(config: OpenSaasConfig, outputPath: string): void {
  const lists = generateListsNamespace(config)

  // Ensure directory exists
  const dir = path.dirname(outputPath)
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true })
  }

  fs.writeFileSync(outputPath, lists, 'utf-8')
}
