import type { OpenSaasConfig } from '@opensaas/stack-core'
import * as fs from 'fs'
import * as path from 'path'

function generatePluginDataInterface(config: OpenSaasConfig): string {
  const lines: string[] = []

  lines.push('/**')
  lines.push(' * Plugin data storage types')
  lines.push(' * Provides type-safe access to config._pluginData')
  lines.push(' */')
  lines.push('export interface PluginData {')

  if (config._pluginData && Object.keys(config._pluginData).length > 0) {
    for (const pluginName of Object.keys(config._pluginData)) {
      // Skip internal keys
      if (pluginName.startsWith('__')) continue

      // TODO: In the future, plugins could export their data types for proper typing
      lines.push(`  ${pluginName}?: Record<string, unknown>`)
    }
  }

  lines.push('}')

  return lines.join('\n')
}

function generatePluginServicesInterface(config: OpenSaasConfig): string {
  const lines: string[] = []
  const imports: string[] = []

  const pluginsWithRuntime = (config._plugins || config.plugins || []).filter((p) => p.runtime)

  if (pluginsWithRuntime.length > 0) {
    for (const plugin of pluginsWithRuntime) {
      if (plugin.runtimeServiceTypes) {
        imports.push(plugin.runtimeServiceTypes.import)
      }
    }
  }

  if (imports.length > 0) {
    lines.push(...imports)
    lines.push('')
  }

  lines.push('/**')
  lines.push(' * Plugin runtime services')
  lines.push(' * Provides type-safe access to context.plugins')
  lines.push(' * Extends Record to allow compatibility with base AccessContext type')
  lines.push(' */')
  lines.push(
    'export interface PluginServices extends Record<string, Record<string, any> | undefined> {',
  )

  if (pluginsWithRuntime.length > 0) {
    for (const plugin of pluginsWithRuntime) {
      if (plugin.runtimeServiceTypes) {
        lines.push(`  ${plugin.name}?: ${plugin.runtimeServiceTypes.typeName}`)
      } else {
        lines.push(`  ${plugin.name}?: Record<string, any>`)
      }
    }
  }

  lines.push('}')

  return lines.join('\n')
}

/**
 * We cannot augment `_pluginData` or `plugins` directly due to type
 * constraints — users must cast to `PluginServices` when accessing
 * `context.plugins`.
 */
function generateModuleAugmentation(): string {
  const lines: string[] = []

  lines.push('')
  lines.push('/**')
  lines.push(' * Declare this module to make interfaces available globally')
  lines.push(' * Import this file to get typed plugin access')
  lines.push(' */')
  lines.push('declare global {')
  lines.push('  // Plugin types are available as PluginServices interface')
  lines.push('}')

  return lines.join('\n')
}

export function generatePluginTypes(config: OpenSaasConfig): string {
  const lines: string[] = []

  lines.push('/**')
  lines.push(' * Generated plugin types from OpenSaas configuration')
  lines.push(' * DO NOT EDIT - This file is automatically generated')
  lines.push(' *')
  lines.push(' * This file provides type-safe access to:')
  lines.push(' * - config._pluginData - Plugin configuration data')
  lines.push(' * - context.plugins - Plugin runtime services')
  lines.push(' */')
  lines.push('')

  lines.push(generatePluginDataInterface(config))
  lines.push(generatePluginServicesInterface(config))

  lines.push(generateModuleAugmentation())

  return lines.join('\n')
}

export function writePluginTypes(config: OpenSaasConfig, outputPath: string): void {
  const pluginTypes = generatePluginTypes(config)

  const dir = path.dirname(outputPath)
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true })
  }

  fs.writeFileSync(outputPath, pluginTypes, 'utf-8')
}
