import * as fs from 'fs'
import * as path from 'path'
import type { ContractData } from '@opensaas/stack-core'

/**
 * The pack's `/control` subpath — the descriptor flavour `defineConfig` takes,
 * as distinct from the `/pack` flavour the Contract module imports (ADR-0049).
 */
function controlSubpath(from: string): string {
  return `${from}/control`
}

/** A single-quoted TypeScript string literal — Windows path separators included. */
function quote(value: string): string {
  return `'${value.replaceAll('\\', '\\\\').replaceAll("'", "\\'")}'`
}

/**
 * What a config written somewhere other than the project root has to say
 * outright, because its own directory no longer answers it: which migrations
 * graph it shares, and whose `.env` it loads.
 */
export interface PrismaConfigLocationOverrides {
  /**
   * The migrations directory. Omitted, the CLI takes its own default beside
   * the config file — right for the project-root config, wrong for a staged
   * one, which must share the project's graph rather than start a private one.
   */
  migrationsDir?: string
  /**
   * The directory whose `.env` is loaded. Defaults to the config file's own
   * directory.
   */
  envDir?: string
}

/**
 * Render the project-root `prisma.config.ts` the Prisma 8 CLI reads.
 *
 * The file wires four things and nothing else: the Contract module's path, the
 * directory the emitted artifacts land in beside it, each declared extension
 * pack's control façade, and the database connection. It never imports
 * `opensaas.config.ts` — the CLI evaluates this file for every command, and a
 * config import would drag the app's plugins, hooks and environment reads onto
 * that path (ADR-0040).
 *
 * The connection is resolved here, so this is also where the project's `.env`
 * is loaded: Prisma's config evaluation loads no dotenv of its own, and
 * ADR-0040's ban on environment reads covers the Contract module, not this
 * file.
 *
 * `definePrismaConfig` stamps the version marker the rc.12 CLI requires; the
 * ORM's own options live under its `orm` section.
 *
 * @param data - The derived contract, read only for its declared extensions.
 * @param contractModule - The Contract module's path relative to the project
 *   root, POSIX-separated (e.g. `./prisma/contract.ts`).
 * @param outputDir - Where `contract.json` and `contract.d.ts` are written —
 *   the Contract module's own directory.
 *
 * @example
 * ```typescript
 * writePrismaConfig(deriveContract(config), '/app/prisma.config.ts', {
 *   contractModule: './prisma/contract.ts',
 *   outputDir: './prisma',
 * })
 * ```
 */
export function generatePrismaConfig(
  data: ContractData,
  contractModule: string,
  outputDir: string,
  overrides: PrismaConfigLocationOverrides = {},
): string {
  const lines: string[] = []

  lines.push('// ⚠️  GENERATED FILE - DO NOT EDIT')
  lines.push("// Generated by 'opensaas generate' from opensaas.config.ts.")
  lines.push('')
  lines.push("import { existsSync } from 'node:fs'")
  lines.push("import { join } from 'node:path'")
  lines.push("import { definePrismaConfig } from 'prisma/config'")
  lines.push("import { defineConfig } from '@prisma/orm-postgres/config'")
  lines.push("import { findDatabaseUrl } from '@opensaas/stack-core'")
  for (const extension of data.extensions) {
    lines.push(`import ${extension.name} from '${controlSubpath(extension.from)}'`)
  }
  lines.push('')
  lines.push('// The Prisma CLI evaluates this file without loading a .env of its own, and')
  lines.push('// `process.loadEnvFile` throws when the file is absent.')
  const envDir = overrides.envDir === undefined ? 'import.meta.dirname' : quote(overrides.envDir)
  lines.push(`const envFile = join(${envDir}, '.env')`)
  lines.push('if (existsSync(envFile)) process.loadEnvFile(envFile)')
  lines.push('')
  lines.push('export default definePrismaConfig({')
  lines.push('  orm: defineConfig({')
  lines.push(`    contract: ${quote(contractModule)},`)
  lines.push(`    output: ${quote(outputDir)},`)
  const packs = data.extensions.map((extension) => extension.name).join(', ')
  lines.push(`    extensions: [${packs}],`)
  if (overrides.migrationsDir !== undefined) {
    lines.push(`    migrations: { dir: ${quote(overrides.migrationsDir)} },`)
  }
  lines.push('    db: { connection: findDatabaseUrl() },')
  lines.push('  }),')
  lines.push('})')
  lines.push('')

  return lines.join('\n')
}

export function writePrismaConfig(
  data: ContractData,
  outputPath: string,
  references: { contractModule: string; outputDir: string } & PrismaConfigLocationOverrides,
): void {
  const content = generatePrismaConfig(data, references.contractModule, references.outputDir, {
    migrationsDir: references.migrationsDir,
    envDir: references.envDir,
  })

  const dir = path.dirname(outputPath)
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true })
  }

  fs.writeFileSync(outputPath, content, 'utf-8')
}
