import * as fs from 'fs'
import * as path from 'path'
import type { ContractData } from '@opensaas/stack-core'

/**
 * The pack's `/control` subpath — the descriptor flavour `defineConfig` takes,
 * as distinct from the `/pack` flavour the Contract module imports (ADR-0049).
 */
function controlSubpath(from: string): string {
  return `${from}/control`
}

/**
 * Render the project-root `prisma.config.ts` the Prisma 8 CLI reads.
 *
 * The file wires four things and nothing else: the Contract module's path, the
 * directory the emitted artifacts land in beside it, each declared extension
 * pack's control façade, and the database connection. It never imports
 * `opensaas.config.ts` — the CLI evaluates this file for every command, and a
 * config import would drag the app's plugins, hooks and environment reads onto
 * that path (ADR-0040).
 *
 * `definePrismaConfig` stamps the version marker the rc.12 CLI requires; the
 * ORM's own options live under its `orm` section.
 *
 * @param data - The derived contract, read only for its declared extensions.
 * @param contractModule - The Contract module's path relative to the project
 *   root, POSIX-separated (e.g. `./prisma/contract.ts`).
 * @param outputDir - Where `contract.json` and `contract.d.ts` are written —
 *   the Contract module's own directory.
 *
 * @example
 * ```typescript
 * writePrismaConfig(deriveContract(config), '/app/prisma.config.ts', {
 *   contractModule: './prisma/contract.ts',
 *   outputDir: './prisma',
 * })
 * ```
 */
export function generatePrismaConfig(
  data: ContractData,
  contractModule: string,
  outputDir: string,
): string {
  const lines: string[] = []

  lines.push('// ⚠️  GENERATED FILE - DO NOT EDIT')
  lines.push("// Generated by 'opensaas generate' from opensaas.config.ts.")
  lines.push('')
  lines.push("import { definePrismaConfig } from 'prisma/config'")
  lines.push("import { defineConfig } from '@prisma/orm-postgres/config'")
  lines.push("import { findDatabaseUrl } from '@opensaas/stack-core'")
  for (const extension of data.extensions) {
    lines.push(`import ${extension.name} from '${controlSubpath(extension.from)}'`)
  }
  lines.push('')
  lines.push('export default definePrismaConfig({')
  lines.push('  orm: defineConfig({')
  lines.push(`    contract: '${contractModule}',`)
  lines.push(`    output: '${outputDir}',`)
  const packs = data.extensions.map((extension) => extension.name).join(', ')
  lines.push(`    extensions: [${packs}],`)
  lines.push('    db: { connection: findDatabaseUrl() },')
  lines.push('  }),')
  lines.push('})')
  lines.push('')

  return lines.join('\n')
}

export function writePrismaConfig(
  data: ContractData,
  outputPath: string,
  references: { contractModule: string; outputDir: string },
): void {
  const content = generatePrismaConfig(data, references.contractModule, references.outputDir)

  const dir = path.dirname(outputPath)
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true })
  }

  fs.writeFileSync(outputPath, content, 'utf-8')
}
