import * as fs from 'fs'
import * as path from 'path'
import type {
  ConstraintMap,
  DependencyTable,
  GeneratedTables,
  ListDependencies,
  UniqueConstraint,
} from '@opensaas/stack-core'

/**
 * Render `<opensaasDir>/tables.ts` — the emitted dependency-set table
 * (ADR-0051) and unique-constraint map (ADR-0042).
 *
 * They sit in the bundle rather than in the Contract module: ADR-0040 makes
 * that artifact standalone, fully literal and Prisma's, and neither table is
 * Prisma's data. The generated context imports this module and hands both to
 * the runtime, which is the door ADR-0051 names — the engine widens a read
 * from an emitted fact instead of walking the config, and a unique violation
 * resolves to per-field messages without parsing prose.
 *
 * Every key is emitted in sorted order so a regenerate over an unchanged
 * config is byte-identical.
 */
function renderStringArray(values: string[]): string {
  return `[${values.map((value) => JSON.stringify(value)).join(', ')}]`
}

function renderListDependencies(listKey: string, entry: ListDependencies): string {
  const fieldKeys = Object.keys(entry.fields).sort()
  const lines = [
    `  ${JSON.stringify(listKey)}: {`,
    `    systemFields: ${renderStringArray(entry.systemFields)},`,
  ]
  if (fieldKeys.length === 0) {
    lines.push('    fields: {},', '  },')
    return lines.join('\n')
  }
  lines.push('    fields: {')
  for (const fieldKey of fieldKeys) {
    const set = entry.fields[fieldKey]
    lines.push(
      `      ${JSON.stringify(fieldKey)}: { columns: ${renderStringArray(set.columns)}, relations: ${renderStringArray(set.relations)} },`,
    )
  }
  lines.push('    },', '  },')
  return lines.join('\n')
}

function renderDependencyTable(table: DependencyTable): string {
  const lines = ['export const dependencyTable: DependencyTable = {']
  for (const listKey of Object.keys(table).sort()) {
    lines.push(renderListDependencies(listKey, table[listKey]))
  }
  lines.push('}')
  return lines.join('\n')
}

function renderConstraint(name: string, entry: UniqueConstraint): string {
  return `  ${JSON.stringify(name)}: { list: ${JSON.stringify(entry.list)}, fields: ${renderStringArray(entry.fields)} },`
}

function renderConstraintMap(map: ConstraintMap): string {
  const lines = ['export const constraintMap: ConstraintMap = {']
  for (const name of Object.keys(map).sort()) {
    lines.push(renderConstraint(name, map[name]))
  }
  lines.push('}')
  return lines.join('\n')
}

/** The bundle's `tables.ts`: both emitted tables as literal, erasable TypeScript. */
export function generateTables(tables: GeneratedTables): string {
  return `/**
 * Auto-generated dependency-set table and unique-constraint map
 *
 * DO NOT EDIT - This file is automatically generated by 'pnpm generate'
 *
 * \`dependencyTable\` is each computed field's one-hop \`needs\` set plus each
 * list's actual system fields (ADR-0051). \`constraintMap\` names every unique
 * constraint the generator emitted, so a unique violation resolves to
 * per-field messages without parsing prose (ADR-0042).
 */

import type { ConstraintMap, DependencyTable } from '@opensaas/stack-core'

${renderDependencyTable(tables.dependencies)}

${renderConstraintMap(tables.constraints)}
`
}

export function writeTables(tables: GeneratedTables, outputPath: string): void {
  const dir = path.dirname(outputPath)
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true })
  }

  fs.writeFileSync(outputPath, generateTables(tables), 'utf-8')
}
