import { config, list } from '@opensaas/stack-core'
import { text, relationship, select, timestamp } from '@opensaas/stack-core/fields'
import { authPlugin } from '@opensaas/stack-auth'
import type { AccessControl } from '@opensaas/stack-core'
import type { Lists } from '@/.opensaas/lists'
import { PrismaBetterSqlite3 } from '@prisma/adapter-better-sqlite3'

/**
 * Access control helpers
 */

// Check if user is signed in. Typed by its parameter (`Parameters<AccessControl>[0]`)
// rather than as a whole `: AccessControl`, with an explicit `boolean` return: this
// helper is reused for both operation-level access (list-level `create`) and
// field-level access (per-field `create`), and only the former accepts a Prisma
// filter — field access is a per-field visibility decision, not a row filter. Since
// this helper never returns a filter, pinning its return type to `boolean` keeps it
// valid at both call sites.
const isSignedIn = ({ session }: Parameters<AccessControl>[0]): boolean => {
  return !!session
}

// Check if user is the author of a post. Scopes ROWS, so it stays `AccessControl`
// (filter-returning) and is used only at the operation level below — field-level
// access cannot honour a filter, see the per-field `access` checks on Post's fields,
// which compare `item.authorId` directly and return a `boolean`.
const isAuthor: AccessControl = ({ session }) => {
  if (!session) return false
  return {
    authorId: { equals: session.userId },
  }
}

/**
 * OpenSaas Configuration with Better-Auth
 */
export default config({
  plugins: [
    authPlugin({
      // Enable email/password authentication
      emailAndPassword: {
        enabled: true,
        minPasswordLength: 8,
        requireConfirmation: true,
      },

      // Enable password reset
      passwordReset: {
        enabled: true,
      },

      // Configure session fields
      sessionFields: ['userId', 'email', 'name'],

      // Extend User list with custom fields
      extendUserList: {
        fields: {
          // Add a posts relationship
          posts: relationship({
            ref: 'Post.author',
            many: true,
          }),
        },
      },

      // The User list ships closed by default (ADR-0013) — grant access
      // explicitly. Signed-in users can browse the directory; only the
      // account owner can update or delete their own record.
      access: {
        user: {
          operation: {
            query: isSignedIn,
            update: ({ session, item }) => session?.userId === item.id,
            delete: ({ session, item }) => session?.userId === item.id,
          },
        },
      },
    }),
  ],

  db: {
    provider: 'sqlite',
    prismaClientConstructor: (PrismaClient) => {
      const adapter = new PrismaBetterSqlite3({ url: process.env.DATABASE_URL || './dev.db' })
      return new PrismaClient({ adapter })
    },
  },

  lists: {
    // User list is auto-generated by authPlugin, but we can reference it
    Post: list<Lists.Post.TypeInfo>({
      fields: {
        title: text({
          validation: { isRequired: true },
          access: {
            read: () => true,
            create: isSignedIn,
            // Field-level access is a boolean-only visibility check (it cannot
            // scope rows like `isAuthor`'s filter does at the operation level
            // above), so this compares `item.authorId` directly.
            update: ({ session, item }) => !!session && session.userId === item?.authorId,
          },
        }),
        slug: text({
          validation: { isRequired: true },
          isIndexed: 'unique',
        }),
        content: text({
          ui: { displayMode: 'textarea' },
          access: {
            read: () => true,
            create: isSignedIn,
            update: ({ session, item }) => !!session && session.userId === item?.authorId,
          },
        }),
        internalNotes: text({
          ui: { displayMode: 'textarea' },
          // Only the author can read/write internal notes. There's no `item`
          // yet on create, so "signed in" is the create-time check — the
          // author is the person creating the post; read/update compare the
          // signed-in session against the item's actual author.
          access: {
            read: ({ session, item }) => !!session && session.userId === item?.authorId,
            create: isSignedIn,
            update: ({ session, item }) => !!session && session.userId === item?.authorId,
          },
        }),
        status: select({
          options: [
            { label: 'Draft', value: 'draft' },
            { label: 'Published', value: 'published' },
          ],
          defaultValue: 'draft',
          ui: { displayMode: 'segmented-control' },
        }),
        publishedAt: timestamp(),
        author: relationship({
          ref: 'User.posts',
        }),
      },
      access: {
        operation: {
          // Non-authenticated users can only see published posts
          // Authenticated users can see all posts
          query: ({ session }) => {
            if (!session) {
              return { status: { equals: 'published' } }
            }
            return true
          },
          // Must be signed in to create
          create: isSignedIn,
          // Only author can update
          update: isAuthor,
          // Only author can delete
          delete: isAuthor,
        },
      },
      hooks: {
        // Auto-set publishedAt when status changes to published
        resolveInput: async ({ operation, resolvedData, item }) => {
          // If changing status to published and publishedAt isn't set yet
          if (operation === 'create' && resolvedData?.status === 'published') {
            return {
              ...resolvedData,
              publishedAt: new Date(),
            }
          } else if (
            operation === 'update' &&
            resolvedData?.status === 'published' &&
            !item?.publishedAt
          ) {
            return {
              ...resolvedData,
              publishedAt: new Date(),
            }
          }
          return { ...resolvedData }
        },
        // Example validation: title must not contain "spam"
        validateInput: async (args) => {
          if (args.operation === 'delete') return
          const { resolvedData, addValidationError } = args
          if (
            resolvedData.title &&
            typeof resolvedData.title === 'string' &&
            resolvedData.title.toLowerCase().includes('spam')
          ) {
            addValidationError('Title cannot contain the word "spam"')
          }
        },
      },
    }),
  },

  ui: {
    basePath: '/admin',
  },
})
