// ⚠️  GENERATED FILE - DO NOT EDIT
// Generated by 'opensaas generate' from opensaas.config.ts.

import { defineContract } from '@prisma/orm-postgres/contract-builder'
import type { ScalarFieldBuilder } from '@prisma/orm-postgres/contract-builder'
import { timestamptzStringColumn } from '@prisma/orm-postgres/adapter/column-types'

type ModelToken = {
  readonly stageOne: {
    readonly modelName?: string
    readonly fields: Record<string, ScalarFieldBuilder>
  }
}

export const contract = defineContract(
  { extensions: {} },
  ({ field, model, rel }) => {
    const models: Record<string, ModelToken> = {}

    const model_Post = (models.Post = model('Post', {
      fields: {
        id: field.id.uuidv7Native(),
        title: field.text(),
        slug: field.text().unique(),
        content: field.text().optional(),
        status: field.text().default('draft'),
        publishedAt: field.column(timestamptzStringColumn).optional(),
        authorId: field.uuidNative().optional().column('author'),
      },
      relations: {
        author: rel.belongsTo(() => models.User, { from: 'authorId', to: 'id' }),
      },
    }))

    const model_User = (models.User = model('User', {
      fields: {
        id: field.id.uuidv7Native(),
        name: field.text(),
        email: field.text().unique(),
        emailVerified: field.boolean().default(false),
        image: field.text().optional(),
        createdAt: field.temporal.createdAtString(),
        updatedAt: field.temporal.updatedAtString(),
      },
      relations: {
        sessions: rel.hasMany(() => models.Session, { by: 'userId' }),
        accounts: rel.hasMany(() => models.Account, { by: 'userId' }),
        oauthClients: rel.hasMany(() => models.OauthClient, { by: 'userId' }),
        oauthRefreshTokens: rel.hasMany(() => models.OauthRefreshToken, { by: 'userId' }),
        oauthAccessTokens: rel.hasMany(() => models.OauthAccessToken, { by: 'userId' }),
        oauthConsents: rel.hasMany(() => models.OauthConsent, { by: 'userId' }),
        posts: rel.hasMany(() => models.Post, { by: 'authorId' }),
      },
    }))

    const model_Session = (models.Session = model('Session', {
      fields: {
        id: field.id.uuidv7Native(),
        token: field.text().unique(),
        expiresAt: field.column(timestamptzStringColumn),
        ipAddress: field.text().optional(),
        userAgent: field.text().optional(),
        userId: field.uuidNative(),
        createdAt: field.temporal.createdAtString(),
        updatedAt: field.temporal.updatedAtString(),
      },
      relations: {
        user: rel.belongsTo(() => models.User, { from: 'userId', to: 'id' }),
        oauthRefreshTokens: rel.hasMany(() => models.OauthRefreshToken, { by: 'sessionId' }),
        oauthAccessTokens: rel.hasMany(() => models.OauthAccessToken, { by: 'sessionId' }),
      },
    }))

    const model_Account = (models.Account = model('Account', {
      fields: {
        id: field.id.uuidv7Native(),
        accountId: field.text(),
        providerId: field.text(),
        issuer: field.text(),
        userId: field.uuidNative(),
        accessToken: field.text().optional(),
        refreshToken: field.text().optional(),
        accessTokenExpiresAt: field.column(timestamptzStringColumn).optional(),
        refreshTokenExpiresAt: field.column(timestamptzStringColumn).optional(),
        scope: field.text().optional(),
        idToken: field.text().optional(),
        password: field.text().optional(),
        createdAt: field.temporal.createdAtString(),
        updatedAt: field.temporal.updatedAtString(),
      },
      relations: {
        user: rel.belongsTo(() => models.User, { from: 'userId', to: 'id' }),
      },
    }))

    const model_Verification = (models.Verification = model('Verification', {
      fields: {
        id: field.id.uuidv7Native(),
        identifier: field.text(),
        value: field.text(),
        expiresAt: field.column(timestamptzStringColumn),
        createdAt: field.temporal.createdAtString(),
        updatedAt: field.temporal.updatedAtString(),
      },
      relations: {},
    }))

    const model_Jwks = (models.Jwks = model('Jwks', {
      fields: {
        id: field.id.uuidv7Native(),
        publicKey: field.text(),
        privateKey: field.text(),
        createdAt: field.column(timestamptzStringColumn),
        expiresAt: field.column(timestamptzStringColumn).optional(),
        alg: field.text().optional(),
        crv: field.text().optional(),
      },
      relations: {},
    }))

    const model_OauthClient = (models.OauthClient = model('OauthClient', {
      fields: {
        id: field.id.uuidv7Native(),
        clientId: field.text().unique(),
        clientSecret: field.text().optional(),
        clientDiscoveryId: field.text().optional(),
        disabled: field.boolean().optional().default(false),
        skipConsent: field.boolean().optional(),
        enableEndSession: field.boolean().optional(),
        subjectType: field.text().optional(),
        scopes: field.text().optional(),
        clientCredentialsScopes: field.text().optional(),
        name: field.text().optional(),
        uri: field.text().optional(),
        icon: field.text().optional(),
        contacts: field.text().optional(),
        tos: field.text().optional(),
        policy: field.text().optional(),
        softwareId: field.text().optional(),
        softwareVersion: field.text().optional(),
        softwareStatement: field.text().optional(),
        redirectUris: field.text(),
        postLogoutRedirectUris: field.text().optional(),
        backchannelLogoutUri: field.text().optional(),
        backchannelLogoutSessionRequired: field.boolean().optional(),
        tokenEndpointAuthMethod: field.text().optional(),
        applicationType: field.text().optional(),
        jwks: field.text().optional(),
        jwksUri: field.text().optional(),
        grantTypes: field.text().optional(),
        responseTypes: field.text().optional(),
        requirePKCE: field.boolean().optional(),
        dpopBoundAccessTokens: field.boolean().optional().default(false),
        referenceId: field.text().optional(),
        metadata: field.text().optional(),
        userId: field.uuidNative().optional(),
        createdAt: field.temporal.createdAtString(),
        updatedAt: field.temporal.updatedAtString(),
      },
      relations: {
        user: rel.belongsTo(() => models.User, { from: 'userId', to: 'id' }),
      },
    }))

    const model_OauthResource = (models.OauthResource = model('OauthResource', {
      fields: {
        id: field.id.uuidv7Native(),
        identifier: field.text().unique(),
        name: field.text(),
        accessTokenTtl: field.int().optional(),
        refreshTokenTtl: field.int().optional(),
        signingAlgorithm: field.text().optional(),
        signingKeyId: field.text().optional(),
        allowedScopes: field.text().optional(),
        customClaims: field.text().optional(),
        dpopBoundAccessTokensRequired: field.boolean().optional().default(false),
        disabled: field.boolean().optional().default(false),
        policyVersion: field.int().optional().default(1),
        metadata: field.text().optional(),
        createdAt: field.temporal.createdAtString(),
        updatedAt: field.temporal.updatedAtString(),
      },
      relations: {},
    }))

    const model_OauthClientResource = (models.OauthClientResource = model('OauthClientResource', {
      fields: {
        id: field.id.uuidv7Native(),
        clientId: field.text(),
        resourceId: field.text(),
        metadata: field.text().optional(),
        createdAt: field.column(timestamptzStringColumn).optional(),
      },
      relations: {},
    }))

    const model_OauthRefreshToken = (models.OauthRefreshToken = model('OauthRefreshToken', {
      fields: {
        id: field.id.uuidv7Native(),
        token: field.text().unique(),
        clientId: field.text(),
        referenceId: field.text().optional(),
        authorizationCodeId: field.text().optional(),
        resources: field.text().optional(),
        requestedUserInfoClaims: field.text().optional(),
        expiresAt: field.column(timestamptzStringColumn),
        createdAt: field.column(timestamptzStringColumn),
        revoked: field.column(timestamptzStringColumn).optional(),
        rotatedAt: field.column(timestamptzStringColumn).optional(),
        rotationReplayResponse: field.text().optional(),
        rotationReplayExpiresAt: field.column(timestamptzStringColumn).optional(),
        authTime: field.column(timestamptzStringColumn).optional(),
        confirmation: field.text().optional(),
        scopes: field.text(),
        sessionId: field.uuidNative().optional(),
        userId: field.uuidNative(),
      },
      relations: {
        session: rel.belongsTo(() => models.Session, { from: 'sessionId', to: 'id' }),
        user: rel.belongsTo(() => models.User, { from: 'userId', to: 'id' }),
        oauthAccessTokens: rel.hasMany(() => models.OauthAccessToken, { by: 'refreshId' }),
      },
    }))

    const model_OauthAccessToken = (models.OauthAccessToken = model('OauthAccessToken', {
      fields: {
        id: field.id.uuidv7Native(),
        token: field.text().unique(),
        clientId: field.text(),
        referenceId: field.text().optional(),
        authorizationCodeId: field.text().optional(),
        resources: field.text().optional(),
        requestedUserInfoClaims: field.text().optional(),
        expiresAt: field.column(timestamptzStringColumn),
        createdAt: field.column(timestamptzStringColumn),
        revoked: field.column(timestamptzStringColumn).optional(),
        confirmation: field.text().optional(),
        scopes: field.text(),
        sessionId: field.uuidNative().optional(),
        userId: field.uuidNative().optional(),
        refreshId: field.uuidNative().optional(),
      },
      relations: {
        session: rel.belongsTo(() => models.Session, { from: 'sessionId', to: 'id' }),
        user: rel.belongsTo(() => models.User, { from: 'userId', to: 'id' }),
        refresh: rel.belongsTo(() => models.OauthRefreshToken, { from: 'refreshId', to: 'id' }),
      },
    }))

    const model_OauthConsent = (models.OauthConsent = model('OauthConsent', {
      fields: {
        id: field.id.uuidv7Native(),
        clientId: field.text(),
        referenceId: field.text().optional(),
        resources: field.text().optional(),
        requestedUserInfoClaims: field.text().optional(),
        scopes: field.text(),
        userId: field.uuidNative().optional(),
        createdAt: field.temporal.createdAtString(),
        updatedAt: field.temporal.updatedAtString(),
      },
      relations: {
        user: rel.belongsTo(() => models.User, { from: 'userId', to: 'id' }),
      },
    }))

    const model_OauthClientAssertion = (models.OauthClientAssertion = model('OauthClientAssertion', {
      fields: {
        id: field.id.uuidv7Native(),
        expiresAt: field.column(timestamptzStringColumn),
      },
      relations: {},
    }))

    return {
      models: {
        Post: model_Post.attributes(() => ({
          uniques: [],
        })).sql(({ cols, constraints }) => ({
          indexes: [
            constraints.index([cols.authorId]),
          ],
          foreignKeys: [
            constraints.foreignKey(cols.authorId, model_User.refs.id, { index: false }),
          ],
        })),
        User: model_User.attributes(() => ({
          uniques: [],
        })).sql(() => ({
          indexes: [],
          foreignKeys: [],
        })),
        Session: model_Session.attributes(() => ({
          uniques: [],
        })).sql(({ cols, constraints }) => ({
          indexes: [
            constraints.index([cols.userId]),
          ],
          foreignKeys: [
            constraints.foreignKey(cols.userId, model_User.refs.id, { index: false, onDelete: 'cascade' }),
          ],
        })),
        Account: model_Account.attributes(() => ({
          uniques: [],
        })).sql(({ cols, constraints }) => ({
          indexes: [
            constraints.index([cols.userId]),
          ],
          foreignKeys: [
            constraints.foreignKey(cols.userId, model_User.refs.id, { index: false, onDelete: 'cascade' }),
          ],
        })),
        Verification: model_Verification.attributes(() => ({
          uniques: [],
        })).sql(({ cols, constraints }) => ({
          indexes: [
            constraints.index([cols.identifier]),
          ],
          foreignKeys: [],
        })),
        Jwks: model_Jwks.attributes(() => ({
          uniques: [],
        })).sql(() => ({
          table: 'jwks',
          indexes: [],
          foreignKeys: [],
        })),
        OauthClient: model_OauthClient.attributes(() => ({
          uniques: [],
        })).sql(({ cols, constraints }) => ({
          table: 'oauthClient',
          indexes: [
            constraints.index([cols.userId]),
          ],
          foreignKeys: [
            constraints.foreignKey(cols.userId, model_User.refs.id, { index: false, onDelete: 'cascade' }),
          ],
        })),
        OauthResource: model_OauthResource.attributes(() => ({
          uniques: [],
        })).sql(() => ({
          table: 'oauthResource',
          indexes: [],
          foreignKeys: [],
        })),
        OauthClientResource: model_OauthClientResource.attributes(() => ({
          uniques: [],
        })).sql(({ cols, constraints }) => ({
          table: 'oauthClientResource',
          indexes: [
            constraints.index([cols.clientId]),
            constraints.index([cols.resourceId]),
          ],
          foreignKeys: [],
        })),
        OauthRefreshToken: model_OauthRefreshToken.attributes(() => ({
          uniques: [],
        })).sql(({ cols, constraints }) => ({
          table: 'oauthRefreshToken',
          indexes: [
            constraints.index([cols.clientId]),
            constraints.index([cols.authorizationCodeId]),
            constraints.index([cols.sessionId]),
            constraints.index([cols.userId]),
          ],
          foreignKeys: [
            constraints.foreignKey(cols.sessionId, model_Session.refs.id, { index: false, onDelete: 'setNull' }),
            constraints.foreignKey(cols.userId, model_User.refs.id, { index: false, onDelete: 'cascade' }),
          ],
        })),
        OauthAccessToken: model_OauthAccessToken.attributes(() => ({
          uniques: [],
        })).sql(({ cols, constraints }) => ({
          table: 'oauthAccessToken',
          indexes: [
            constraints.index([cols.clientId]),
            constraints.index([cols.authorizationCodeId]),
            constraints.index([cols.sessionId]),
            constraints.index([cols.userId]),
            constraints.index([cols.refreshId]),
          ],
          foreignKeys: [
            constraints.foreignKey(cols.sessionId, model_Session.refs.id, { index: false, onDelete: 'setNull' }),
            constraints.foreignKey(cols.userId, model_User.refs.id, { index: false, onDelete: 'cascade' }),
            constraints.foreignKey(cols.refreshId, model_OauthRefreshToken.refs.id, { index: false, onDelete: 'cascade' }),
          ],
        })),
        OauthConsent: model_OauthConsent.attributes(() => ({
          uniques: [],
        })).sql(({ cols, constraints }) => ({
          table: 'oauthConsent',
          indexes: [
            constraints.index([cols.clientId]),
            constraints.index([cols.userId]),
          ],
          foreignKeys: [
            constraints.foreignKey(cols.userId, model_User.refs.id, { index: false, onDelete: 'cascade' }),
          ],
        })),
        OauthClientAssertion: model_OauthClientAssertion.attributes(() => ({
          uniques: [],
        })).sql(() => ({
          table: 'oauthClientAssertion',
          indexes: [],
          foreignKeys: [],
        })),
      },
    }
  },
)
