// ⚠️  GENERATED FILE - DO NOT EDIT
// Generated by 'opensaas generate' from opensaas.config.ts.

import { defineContract } from '@prisma/orm-postgres/contract-builder'
import type { ScalarFieldBuilder } from '@prisma/orm-postgres/contract-builder'
import { dateStringColumn, timestamptzStringColumn } from '@prisma/orm-postgres/adapter/column-types'

type ModelToken = {
  readonly stageOne: {
    readonly modelName?: string
    readonly fields: Record<string, ScalarFieldBuilder>
  }
}

export const contract = defineContract(
  { extensions: {} },
  ({ field, model, rel }) => {
    const models: Record<string, ModelToken> = {}

    const model_Settings = (models.Settings = model('Settings', {
      fields: {
        id: field.int().default(1).id(),
        siteName: field.text().default('My Blog'),
        maintenanceMode: field.boolean().default(false),
        maxUploadSize: field.int().optional().default(10),
        createdAt: field.temporal.createdAtString(),
        updatedAt: field.temporal.updatedAtString(),
      },
      relations: {},
    }))

    const model_User = (models.User = model('User', {
      fields: {
        id: field.id.uuidv7Native(),
        name: field.text(),
        email: field.text().unique(),
        password: field.text(),
        createdAt: field.temporal.createdAtString(),
        updatedAt: field.temporal.updatedAtString(),
      },
      relations: {
        posts: rel.hasMany(() => models.Post, { by: 'authorId' }),
      },
    }))

    const model_Post = (models.Post = model('Post', {
      fields: {
        id: field.id.uuidv7Native(),
        title: field.text(),
        slug: field.text().unique(),
        content: field.text().optional(),
        internalNotes: field.text().optional(),
        status: field.text().default('draft'),
        publishDate: field.column(dateStringColumn).optional().column('publish_date'),
        publishedAt: field.column(timestamptzStringColumn).optional(),
        authorId: field.uuidNative().optional().column('author'),
        createdAt: field.temporal.createdAtString(),
        updatedAt: field.temporal.updatedAtString(),
      },
      relations: {
        author: rel.belongsTo(() => models.User, { from: 'authorId', to: 'id' }),
        tags: rel.hasMany(() => models.PostTag, { by: 'postId' }),
      },
    }))

    const model_Tag = (models.Tag = model('Tag', {
      fields: {
        id: field.id.uuidv7Native(),
        name: field.text().unique(),
        createdAt: field.temporal.createdAtString(),
        updatedAt: field.temporal.updatedAtString(),
      },
      relations: {
        posts: rel.hasMany(() => models.PostTag, { by: 'tagId' }),
      },
    }))

    const model_PostTag = (models.PostTag = model('PostTag', {
      fields: {
        id: field.id.uuidv7Native(),
        postId: field.uuidNative().optional().column('post'),
        tagId: field.uuidNative().optional().column('tag'),
        createdAt: field.temporal.createdAtString(),
        updatedAt: field.temporal.updatedAtString(),
      },
      relations: {
        post: rel.belongsTo(() => models.Post, { from: 'postId', to: 'id' }),
        tag: rel.belongsTo(() => models.Tag, { from: 'tagId', to: 'id' }),
      },
    }))

    return {
      models: {
        Settings: model_Settings.attributes(() => ({
          uniques: [],
        })).sql(() => ({
          indexes: [],
          foreignKeys: [],
        })),
        User: model_User.attributes(() => ({
          uniques: [],
        })).sql(() => ({
          indexes: [],
          foreignKeys: [],
        })),
        Post: model_Post.attributes(() => ({
          uniques: [],
        })).sql(({ cols, constraints }) => ({
          indexes: [
            constraints.index([cols.title]),
            constraints.index([cols.authorId]),
          ],
          foreignKeys: [
            constraints.foreignKey(cols.authorId, model_User.refs.id, { index: false }),
          ],
        })),
        Tag: model_Tag.attributes(() => ({
          uniques: [],
        })).sql(() => ({
          indexes: [],
          foreignKeys: [],
        })),
        PostTag: model_PostTag.attributes(({ fields, constraints }) => ({
          uniques: [
            constraints.unique([fields.postId, fields.tagId], {}),
          ],
        })).sql(({ cols, constraints }) => ({
          indexes: [
            constraints.index([cols.postId]),
            constraints.index([cols.tagId]),
          ],
          foreignKeys: [
            constraints.foreignKey(cols.postId, model_Post.refs.id, { index: false }),
            constraints.foreignKey(cols.tagId, model_Tag.refs.id, { index: false }),
          ],
        })),
      },
    }
  },
)
