/**
 * MCP (Model Context Protocol) integration for RAG
 *
 * MCP tools for semantic search are automatically generated by the ragPlugin.
 * This export is provided for future extensibility and custom MCP tool generation.
 */

// Re-export types that may be useful for MCP tool development
export type { SearchResult } from '../config/types.js'
export type { SemanticSearchOptions } from '../runtime/search.js'

/**
 * MCP tools are automatically generated by ragPlugin when:
 * - MCP is enabled in main config
 * - ragPlugin has enableMcpTools: true (default)
 *
 * Generated tools:
 * - semantic_search_{listKey} - Search by natural language query
 *
 * See packages/rag/src/config/plugin.ts for implementation details.
 */
