// ⚠️  GENERATED FILE - DO NOT EDIT
// Generated by 'opensaas generate' from opensaas.config.ts.

import { defineContract } from '@prisma/orm-postgres/contract-builder'
import type { ScalarFieldBuilder } from '@prisma/orm-postgres/contract-builder'
import pgvector from '@prisma/orm-extension-pgvector/pack'

type ModelToken = {
  readonly stageOne: {
    readonly modelName?: string
    readonly fields: Record<string, ScalarFieldBuilder>
  }
}

export const contract = defineContract(
  { extensions: { pgvector } },
  ({ field, model, type }) => {
    const models: Record<string, ModelToken> = {}

    const model_Document = (models.Document = model('Document', {
      fields: {
        id: field.id.uuidv7Native(),
        title: field.text(),
        content: field.text(),
        summary: field.text().optional(),
        published: field.boolean().default(false),
        contentEmbedding: field.column(type.pgvector.Vector(768)).optional(),
        contentEmbeddingMetadata: field.json().optional(),
      },
      relations: {},
    }))

    const model_Article = (models.Article = model('Article', {
      fields: {
        id: field.id.uuidv7Native(),
        title: field.text(),
        body: field.text(),
        category: field.text().optional(),
        published: field.boolean().default(false),
        bodyEmbedding: field.column(type.pgvector.Vector(768)).optional(),
        bodyEmbeddingMetadata: field.json().optional(),
      },
      relations: {},
    }))

    return {
      models: {
        Document: model_Document.attributes(() => ({
          uniques: [],
        })).sql(() => ({
          indexes: [],
          foreignKeys: [],
        })),
        Article: model_Article.attributes(() => ({
          uniques: [],
        })).sql(() => ({
          indexes: [],
          foreignKeys: [],
        })),
      },
    }
  },
)
