// ⚠️  GENERATED FILE - DO NOT EDIT
// Generated by 'opensaas generate' from opensaas.config.ts.

import { defineContract } from '@prisma/orm-postgres/contract-builder'
import type { ScalarFieldBuilder } from '@prisma/orm-postgres/contract-builder'
import pgvector from '@prisma/orm-extension-pgvector/pack'

type ModelToken = {
  readonly stageOne: {
    readonly modelName?: string
    readonly fields: Record<string, ScalarFieldBuilder>
  }
}

export const contract = defineContract(
  { extensions: { pgvector } },
  ({ field, model, type }) => {
    const models: Record<string, ModelToken> = {}

    const model_KnowledgeBase = (models.KnowledgeBase = model('KnowledgeBase', {
      fields: {
        id: field.id.uuidv7Native(),
        title: field.text(),
        content: field.text(),
        contentEmbedding: field.column(type.pgvector.Vector(1536)).optional(),
        contentEmbeddingMetadata: field.json().optional(),
        category: field.text(),
        published: field.boolean().default(true),
      },
      relations: {},
    }))

    return {
      models: {
        KnowledgeBase: model_KnowledgeBase.attributes(() => ({
          uniques: [],
        })).sql(() => ({
          indexes: [],
          foreignKeys: [],
        })),
      },
    }
  },
)
